display_name: Bililive
package_name: bililive
maintainer:
  name: xiaoyaocz
  email: xiaoyaocz@52uwp.com
priority: optional
section: x11
installed_size: 24400
essential: false
icon: assets/logo.png

keywords:
  - Bililive

generic_name: Bililive

categories:
  - Media

startup_notify: true
